name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          ref: develop

      - name: Bump version in package.json
        working-directory: packages/web
        run: yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4.1.3
        with:
          commit-message: Prepare release/${{ github.event.inputs.version }}
          committer: GitHub <noreply@github.com>
          base: main
          branch: release/${{ github.event.inputs.version }}
          title: Release version ${{ github.event.inputs.version }}
          labels: |
            release
